import json
import math
import os

from flask import Flask, jsonify, render_template, request

from config import DevelopmentConfig, ProductionConfig
from extensions import db, migrate, limiter
from game import BOARD_SIZE, GAME_CONFIG, PIECE_STATS
from game.physics.authoritative import AuthoritativeSimulation
from logging_config import configure_logging
from rooms import create_room

VERSION = "v0.5.2"


def create_app(config_object=DevelopmentConfig):
    application = Flask(__name__)
    application.config.from_object(config_object)
    if config_object is ProductionConfig and not os.environ.get("SECRET_KEY"):
        raise RuntimeError("SECRET_KEY must be set in production")

    db.init_app(application)
    migrate.init_app(application, db)
    limiter.init_app(application)
    configure_logging(application)

    def load_simulation(room):
        if room.canonical_state:
            return AuthoritativeSimulation.from_snapshot(json.loads(room.canonical_state))
        return AuthoritativeSimulation.new_match()

    def winner_from_snapshot(snapshot):
        white_dead = next((not p["alive"] or p["hp"] <= 0 for p in snapshot["pieces"] if p["type"] == "king" and p["team"] == "white"), True)
        black_dead = next((not p["alive"] or p["hp"] <= 0 for p in snapshot["pieces"] if p["type"] == "king" and p["team"] == "black"), True)
        if white_dead and black_dead:
            return snapshot.get("currentTeam", "white")
        if white_dead:
            return "black"
        if black_dead:
            return "white"
        return None

    def persist_simulation(room, simulation, events=None):
        snapshot = simulation.snapshot()
        serialized = json.dumps(snapshot, separators=(",", ":"), sort_keys=True)
        room.canonical_state = serialized
        room.last_physics_state = serialized
        room.last_hp_state = json.dumps(
            {piece["id"]: {"hp": piece["hp"], "alive": piece["alive"]} for piece in snapshot["pieces"]},
            separators=(",", ":"),
            sort_keys=True,
        )
        destroyed = [event["destroyed"] for event in (events or []) if event.get("destroyed")]
        if destroyed:
            room.last_destruction_event = json.dumps(
                {"pieceIds": [piece_id for batch in destroyed for piece_id in batch]},
                separators=(",", ":"),
                sort_keys=True,
            )
        if simulation.game_over:
            room.status = "finished"
            room.last_gameover_event = json.dumps(
                {"winner": winner_from_snapshot(snapshot)},
                separators=(",", ":"),
                sort_keys=True,
            )
        room.current_turn = simulation.current_team
        db.session.commit()
        return snapshot

    def reject_client_state():
        return jsonify({
            "error": "client_state_not_authoritative",
            "message": "Active multiplayer state is generated by the server simulation",
        }), 409

    @application.get("/")
    def index():
        return render_template("index.html")

    @application.get("/api/game/config")
    def game_config():
        return jsonify({
            "version": VERSION,
            "boardSize": BOARD_SIZE,
            "pieceStats": PIECE_STATS,
            "gameConfig": GAME_CONFIG,
        })

    @application.get("/api/version")
    def get_version():
        return jsonify({"version": VERSION})

    @application.get("/api/health")
    def health_check():
        return jsonify({"status": "ok", "version": VERSION})

    @limiter.limit("5 per minute")
    @application.post("/api/rooms")
    def create_game_room():
        payload = request.get_json(silent=True) or {}
        guest_id = payload.get("guestId")
        if not isinstance(guest_id, str) or not guest_id.strip() or len(guest_id) > 100:
            return jsonify({"error": "invalid_guest_id", "message": "A valid guestId is required"}), 400
        return jsonify(create_room(guest_id.strip())), 201

    @application.get("/api/rooms/<room_code>/hp")
    def get_hp_state(room_code):
        from game.models import Room
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        return jsonify({"hpState": room.last_hp_state}), 200

    @application.post("/api/rooms/<room_code>/hp")
    def sync_hp(room_code):
        return reject_client_state()

    @application.get("/api/rooms/<room_code>/destruction")
    def get_destruction_state(room_code):
        from game.models import Room
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        return jsonify({"destructionEvent": room.last_destruction_event}), 200

    @application.post("/api/rooms/<room_code>/destruction")
    def sync_destruction(room_code):
        return reject_client_state()

    @application.get("/api/rooms/<room_code>/sync")
    def get_physics_state(room_code):
        from game.models import Room
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        return jsonify({"state": room.last_physics_state}), 200

    @application.post("/api/rooms/<room_code>/sync")
    def sync_physics(room_code):
        return reject_client_state()

    @application.post("/api/rooms/<room_code>/launch")
    def launch_piece(room_code):
        from game.models import Room, User
        payload = request.get_json(silent=True) or {}
        guest_id = payload.get("guestId")
        launch_data = payload.get("launchData")

        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        if room.status != "active":
            return jsonify({"error": "room_not_active"}), 409

        user = User.query.filter_by(guest_id=guest_id).first()
        if not user or user.room_id != room.id:
            return jsonify({"error": "unauthorized"}), 403

        team = "white" if user.id == room.white_player_id else "black" if user.id == room.black_player_id else None
        if team is None:
            return jsonify({"error": "unauthorized"}), 403

        if not isinstance(launch_data, dict):
            return jsonify({"error": "invalid_action", "reason": "Missing or invalid launchData"}), 400
        piece_id = launch_data.get("pieceId")
        if not isinstance(piece_id, str):
            return jsonify({"error": "invalid_action", "reason": "Invalid pieceId"}), 400

        simulation = load_simulation(room)
        mode = "drag" if "drag" in launch_data else "vector"
        try:
            if mode == "drag":
                drag = launch_data.get("drag")
                if not isinstance(drag, dict) or "x" not in drag or "y" not in drag:
                    return jsonify({"error": "invalid_action", "reason": "Invalid drag intent"}), 400
                dx = float(drag["x"])
                dy = float(drag["y"])
                valid, reason = simulation.launch_intent(team, piece_id, dx, dy)
                supplied = {"dx": dx, "dy": dy}
            else:
                vector = launch_data.get("vector")
                if not isinstance(vector, dict) or "x" not in vector or ("y" not in vector and "z" not in vector):
                    return jsonify({"error": "invalid_action", "reason": "Invalid launch intent"}), 400
                vx = float(vector["x"])
                vy = float(vector.get("y", vector.get("z")))
                valid, reason = simulation.validate_launch(team, piece_id, vx, vy)
                if valid:
                    valid, reason = simulation.launch(team, piece_id, vx, vy)
                supplied = {"vx": vx, "vy": vy}
        except (TypeError, ValueError):
            return jsonify({"error": "invalid_action", "reason": "Launch intent must be numeric"}), 400

        if not valid:
            entry = json.dumps({
                "guestId": guest_id,
                "team": team,
                "pieceId": piece_id,
                **supplied,
                "reason": reason,
            }, separators=(",", ":"), sort_keys=True)
            room.invalid_action_log = entry if not room.invalid_action_log else room.invalid_action_log + "\n" + entry
            db.session.commit()
            status = 403 if reason in {"not_your_turn", "piece_not_owned", "piece_dead", "match_over"} else 400
            return jsonify({"error": "invalid_action", "reason": reason}), status

        events = simulation.advance_until_settled()
        snapshot = persist_simulation(room, simulation, events)

        shot_log = json.dumps({
            "guestId": guest_id,
            "team": team,
            "pieceId": piece_id,
            **supplied,
            "events": events,
            "gameOver": simulation.game_over,
        }, separators=(",", ":"), sort_keys=True)
        room.match_log = shot_log if not room.match_log else room.match_log + "\n" + shot_log
        db.session.commit()

        return jsonify({
            "status": "success",
            "state": snapshot,
            "events": events,
            "nextTurn": simulation.current_team,
            "gameOver": simulation.game_over,
            "winner": winner_from_snapshot(snapshot),
        }), 200

    @application.get("/api/rooms/<room_code>/gameover")
    def get_gameover_state(room_code):
        from game.models import Room
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        return jsonify({"gameOverEvent": room.last_gameover_event}), 200

    @application.post("/api/rooms/<room_code>/gameover")
    def sync_gameover(room_code):
        return reject_client_state()

    @application.get("/api/rooms/<room_code>/turn")
    def get_turn(room_code):
        from game.models import Room
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        return jsonify({"currentTeam": room.current_turn}), 200

    @application.post("/api/rooms/<room_code>/start")
    def start_game_room(room_code):
        from game.models import Room
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        if len(room.players) < 2:
            return jsonify({"error": "insufficient_players"}), 400

        simulation = AuthoritativeSimulation.new_match()
        snapshot = simulation.snapshot()
        room.status = "active"
        room.current_turn = "white"
        room.canonical_state = json.dumps(snapshot, separators=(",", ":"), sort_keys=True)
        room.last_physics_state = room.canonical_state
        room.last_hp_state = json.dumps(
            {piece["id"]: {"hp": piece["hp"], "alive": piece["alive"]} for piece in snapshot["pieces"]},
            separators=(",", ":"),
            sort_keys=True,
        )
        room.last_destruction_event = None
        room.last_gameover_event = None
        room.match_log = None
        room.invalid_action_log = None
        db.session.commit()
        return jsonify({"room": room.to_dict(), "state": snapshot}), 200

    @application.post("/api/rooms/<room_code>/join")
    def join_game_room(room_code):
        payload = request.get_json(silent=True) or {}
        guest_id = payload.get("guestId")
        if not isinstance(guest_id, str) or not guest_id.strip() or len(guest_id) > 100:
            return jsonify({"error": "invalid_guest_id", "message": "A valid guestId is required"}), 400

        from game.models import Room, User
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        if room.status != "waiting":
            return jsonify({"error": "room_not_joinable"}), 409

        user = User.query.filter_by(guest_id=guest_id.strip()).first()
        if not user:
            user = User(guest_id=guest_id.strip())
            db.session.add(user)
            db.session.flush()
        if user.room_id == room.id:
            return jsonify(room.to_dict()), 200
        if len(room.players) >= 2:
            return jsonify({"error": "room_full"}), 403

        user.room = room
        if not room.black_player_id:
            room.black_player_id = user.id
        db.session.commit()
        return jsonify(room.to_dict()), 200

    @application.post("/api/rooms/<room_code>/reconnect")
    def reconnect_room(room_code):
        from game.models import Room, User
        payload = request.get_json(silent=True) or {}
        guest_id = payload.get("guestId")
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        user = User.query.filter_by(guest_id=guest_id).first()
        if not user or user.room_id != room.id:
            return jsonify({"error": "unauthorized"}), 403
        return jsonify({
            "status": "reconnected",
            "room": room.to_dict(),
            "state": room.last_physics_state,
            "hpState": room.last_hp_state,
            "destructionEvent": room.last_destruction_event,
            "gameOverEvent": room.last_gameover_event,
            "currentTurn": room.current_turn,
        }), 200

    @application.post("/api/rooms/<room_code>/rematch")
    def rematch_room(room_code):
        from game.models import Room, User
        payload = request.get_json(silent=True) or {}
        guest_id = payload.get("guestId")
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        user = User.query.filter_by(guest_id=guest_id).first()
        if not user or user.room_id != room.id:
            return jsonify({"error": "unauthorized"}), 403

        simulation = AuthoritativeSimulation.new_match()
        snapshot = simulation.snapshot()
        room.status = "active"
        room.current_turn = "white"
        room.canonical_state = json.dumps(snapshot, separators=(",", ":"), sort_keys=True)
        room.last_physics_state = room.canonical_state
        room.last_hp_state = json.dumps(
            {piece["id"]: {"hp": piece["hp"], "alive": piece["alive"]} for piece in snapshot["pieces"]},
            separators=(",", ":"),
            sort_keys=True,
        )
        room.last_destruction_event = None
        room.last_gameover_event = None
        room.match_log = None
        room.invalid_action_log = None
        db.session.commit()
        return jsonify({"status": "rematch_started", "room": room.to_dict(), "state": snapshot}), 200

    @application.post("/api/rooms/<room_code>/disconnect")
    def disconnect_room(room_code):
        from game.models import Room, User
        payload = request.get_json(silent=True) or {}
        guest_id = payload.get("guestId")
        room = Room.query.filter_by(room_code=room_code).first()
        if not room:
            return jsonify({"error": "room_not_found"}), 404
        user = User.query.filter_by(guest_id=guest_id).first()
        if user and user.room_id == room.id:
            user.room_id = None
            room.status = "finished"
            db.session.commit()
            return jsonify({"status": "disconnected"}), 200
        return jsonify({"error": "unauthorized"}), 403

    @application.errorhandler(404)
    def not_found(error):
        return jsonify({"error": "not_found", "message": "Resource not found"}), 404

    @application.errorhandler(500)
    def internal_error(error):
        return jsonify({"error": "internal_server_error", "message": "Internal server error"}), 500

    @application.errorhandler(413)
    def request_too_large(error):
        return jsonify({"error": "request_too_large", "message": "Request payload is too large"}), 413

    @application.after_request
    def add_security_headers(response):
        response.headers.setdefault("X-Content-Type-Options", "nosniff")
        response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
        response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
        response.headers.setdefault("Permissions-Policy", "camera=(), microphone=(), geolocation=()")
        return response

    @application.before_request
    def validate_api_request():
        if request.content_length and request.content_length > application.config["MAX_CONTENT_LENGTH"]:
            return jsonify({"error": "request_too_large", "message": "Request payload is too large"}), 413
        if request.path.startswith("/api/") and request.method in {"POST", "PUT", "PATCH"}:
            if request.content_length and not request.is_json:
                return jsonify({"error": "json_required", "message": "JSON request body required"}), 415
        return None

    @application.get("/api/config")
    def legacy_config():
        return game_config()

    return application


app = create_app()


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
