"""Add room_id to User

Revision ID: 2dd592219425
Revises: 8b77f5b194fb
Create Date: 2026-08-22 18:45:22.040878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2dd592219425"
down_revision = "8b77f5b194fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("room_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_users_room_id_rooms", "rooms", ["room_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_room_id_rooms", type_="foreignkey")
        batch_op.drop_column("room_id")

    # ### end Alembic commands ###