"""add current_turn to rooms

Revision ID: 38476ea52d6a
Revises: 69ee9e25f625
Create Date: 2026-08-23 12:37:31.905476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38476ea52d6a'
down_revision = '69ee9e25f625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_turn', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('current_turn')

    # ### end Alembic commands ###
