"""add last_gameover_event to Room

Revision ID: 44421118313f
Revises: 97b2c23a6b66
Create Date: 2026-08-23 18:21:24.591886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44421118313f'
down_revision = '97b2c23a6b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_gameover_event', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('last_gameover_event')

    # ### end Alembic commands ###
