"""add last_hp_state to rooms

Revision ID: 599e3bc26b31
Revises: 828e2d6281f6
Create Date: 2026-08-23 14:01:28.335421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599e3bc26b31'
down_revision = '828e2d6281f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_hp_state', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('last_hp_state')

    # ### end Alembic commands ###
