"""add team columns to rooms

Revision ID: 69ee9e25f625
Revises: 2dd592219425
Create Date: 2026-08-23 12:13:26.302523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ee9e25f625'
down_revision = '2dd592219425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('white_player_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('black_player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_rooms_white_player_id', 'users', ['white_player_id'], ['id'])
        batch_op.create_foreign_key('fk_rooms_black_player_id', 'users', ['black_player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rooms_white_player_id', type_='foreignkey')
        batch_op.drop_constraint('fk_rooms_black_player_id', type_='foreignkey')
        batch_op.drop_column('black_player_id')
        batch_op.drop_column('white_player_id')

    # ### end Alembic commands ###
