"""Add Step 13 columns to Room

Revision ID: 6e6a459ac812
Revises: b86add9059d3
Create Date: 2026-08-23 18:53:45.558131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6a459ac812'
down_revision = 'b86add9059d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_state', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('match_log', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('invalid_action_log', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('invalid_action_log')
        batch_op.drop_column('match_log')
        batch_op.drop_column('canonical_state')

    # ### end Alembic commands ###
