"""Add MatchmakingQueue and User MMR

Revision ID: 72cba26399f5
Revises: 6e6a459ac812
Create Date: 2026-08-23 19:01:25.140058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cba26399f5'
down_revision = '6e6a459ac812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchmaking_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('matched_room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matched_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matchmaking_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchmaking_queue_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mmr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('matches_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')
        batch_op.drop_column('matches_played')
        batch_op.drop_column('mmr')

    with op.batch_alter_table('matchmaking_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchmaking_queue_user_id'))

    op.drop_table('matchmaking_queue')
    # ### end Alembic commands ###
