"""add last_physics_state to rooms

Revision ID: 828e2d6281f6
Revises: 38476ea52d6a
Create Date: 2026-08-23 12:52:44.383959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828e2d6281f6'
down_revision = '38476ea52d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_physics_state', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('last_physics_state')

    # ### end Alembic commands ###
