"""add last_destruction_event to Room

Revision ID: 97b2c23a6b66
Revises: 599e3bc26b31
Create Date: 2026-08-23 18:13:25.171744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b2c23a6b66'
down_revision = '599e3bc26b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_destruction_event', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('last_destruction_event')

    # ### end Alembic commands ###
